# Generated by Django 4.1.3 on 2022-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0005_rename_super_type_supertype_supers_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='supers_type',
            new_name='type',
        ),
    ]
