# Generated by Django 4.1.3 on 2022-12-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_alter_supers_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_type',
            new_name='supers_type',
        ),
    ]
