# Generated by Django 4.1.3 on 2022-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_super_type_supers_supers_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='supers_type',
            new_name='type',
        ),
    ]
