# Generated by Django 4.1.3 on 2022-12-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0007_rename_type_supertype_super_type'),
        ('supers', '0004_rename_supers_type_supers_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supers',
            name='type',
        ),
        migrations.AddField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
            preserve_default=False,
        ),
    ]
